spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 80Mb
      location: /tmp/tomcat_upload
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 182.61.55.148
    port: 6379
    password: wangankeji # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

server:
#  port: 8083
  port: 8092
  servlet:
    context-path: /

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.qiguliuxing.dts.wx:  DEBUG
    com.qiguliuxing.dts:  INFO