package com.qiguliuxing.dts.db.dao;

import com.qiguliuxing.dts.db.domain.DtsCouponUser;
import com.qiguliuxing.dts.db.domain.DtsCouponUserExample;
import org.apache.ibatis.annotations.Param;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

public interface DtsCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(DtsCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(DtsCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     */
    int insert(DtsCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(DtsCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsCouponUser selectOneByExample(DtsCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsCouponUser selectOneByExampleSelective(@Param("example") DtsCouponUserExample example, @Param("selective") DtsCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DtsCouponUser> selectByExampleSelective(@Param("example") DtsCouponUserExample example, @Param("selective") DtsCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     */
    List<DtsCouponUser> selectByExample(DtsCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DtsCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     */
    DtsCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DtsCouponUser record, @Param("example") DtsCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DtsCouponUser record, @Param("example") DtsCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DtsCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DtsCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") DtsCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);

    /**
     * 使用优惠券，更改优惠券状态
     * @param id
     * @return
     */
    int updateCouponStatusById(@Param("id") Integer id, @Param("now") LocalDateTime now);

    /**
     * 查询用户在该商铺下所拥有的优惠券
     * @param userId
     * @param shopId
     * @param status
     * @return
     */
    List<DtsCouponUser> selectShopCouponList(@Param("userId") Integer userId, @Param("shopId") String shopId, @Param("status") Short status);

    /**
     * 根据优惠券id集合和用户id   更新优惠券使用状态
     * @param userId
     * @param couponIdList
     * @return
     */
    int updateStatusAllByCouponIdList(@Param("userId") Integer userId, @Param("list")Set<Integer> couponIdList,@Param("orderSn")String orderSn);
}