package com.qiguliuxing.dts.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class DtsShopCategoryEntityExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    protected List<DtsShopCategoryEntityExample.Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    public DtsShopCategoryEntityExample() {
        oredCriteria = new ArrayList<DtsShopCategoryEntityExample.Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    public List<DtsShopCategoryEntityExample.Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    public void or(DtsShopCategoryEntityExample.Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    public DtsShopCategoryEntityExample.Criteria or() {
        DtsShopCategoryEntityExample.Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public DtsShopCategoryEntityExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public DtsShopCategoryEntityExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    public DtsShopCategoryEntityExample.Criteria createCriteria() {
        DtsShopCategoryEntityExample.Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    protected DtsShopCategoryEntityExample.Criteria createCriteriaInternal() {
        DtsShopCategoryEntityExample.Criteria criteria = new DtsShopCategoryEntityExample.Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static DtsShopCategoryEntityExample.Criteria newAndCreateCriteria() {
        DtsShopCategoryEntityExample example = new DtsShopCategoryEntityExample();
        return example.createCriteria();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<DtsShopCategoryEntityExample.Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<DtsShopCategoryEntityExample.Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<DtsShopCategoryEntityExample.Criterion> getAllCriteria() {
            return criteria;
        }

        public List<DtsShopCategoryEntityExample.Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new DtsShopCategoryEntityExample.Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new DtsShopCategoryEntityExample.Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new DtsShopCategoryEntityExample.Criterion(condition, value1, value2));
        }

        public DtsShopCategoryEntityExample.Criteria andIdIsNull() {
            addCriterion("id is null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andShopIdEqualTo(Integer value) {
            addCriterion("shop_id =", value, "shopId");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andIdEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andIdNotEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andIdGreaterThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andIdGreaterThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andIdLessThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andIdLessThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andNameEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`name` = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andNameNotEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`name` <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andNameGreaterThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`name` > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andNameGreaterThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`name` >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andNameLessThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`name` < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andNameLessThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`name` <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andKeywordsIsNull() {
            addCriterion("keywords is null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andKeywordsIsNotNull() {
            addCriterion("keywords is not null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andKeywordsEqualTo(String value) {
            addCriterion("keywords =", value, "keywords");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andKeywordsEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("keywords = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andKeywordsNotEqualTo(String value) {
            addCriterion("keywords <>", value, "keywords");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andKeywordsNotEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("keywords <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andKeywordsGreaterThan(String value) {
            addCriterion("keywords >", value, "keywords");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andKeywordsGreaterThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("keywords > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("keywords >=", value, "keywords");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andKeywordsGreaterThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("keywords >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andKeywordsLessThan(String value) {
            addCriterion("keywords <", value, "keywords");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andKeywordsLessThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("keywords < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andKeywordsLessThanOrEqualTo(String value) {
            addCriterion("keywords <=", value, "keywords");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andKeywordsLessThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("keywords <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andKeywordsLike(String value) {
            addCriterion("keywords like", value, "keywords");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andKeywordsNotLike(String value) {
            addCriterion("keywords not like", value, "keywords");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andKeywordsIn(List<String> values) {
            addCriterion("keywords in", values, "keywords");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andKeywordsNotIn(List<String> values) {
            addCriterion("keywords not in", values, "keywords");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andKeywordsBetween(String value1, String value2) {
            addCriterion("keywords between", value1, value2, "keywords");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andKeywordsNotBetween(String value1, String value2) {
            addCriterion("keywords not between", value1, value2, "keywords");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDescIsNull() {
            addCriterion("`desc` is null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDescIsNotNull() {
            addCriterion("`desc` is not null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDescEqualTo(String value) {
            addCriterion("`desc` =", value, "desc");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andDescEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`desc` = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDescNotEqualTo(String value) {
            addCriterion("`desc` <>", value, "desc");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andDescNotEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`desc` <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDescGreaterThan(String value) {
            addCriterion("`desc` >", value, "desc");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andDescGreaterThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`desc` > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDescGreaterThanOrEqualTo(String value) {
            addCriterion("`desc` >=", value, "desc");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andDescGreaterThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`desc` >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDescLessThan(String value) {
            addCriterion("`desc` <", value, "desc");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andDescLessThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`desc` < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDescLessThanOrEqualTo(String value) {
            addCriterion("`desc` <=", value, "desc");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andDescLessThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`desc` <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDescLike(String value) {
            addCriterion("`desc` like", value, "desc");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDescNotLike(String value) {
            addCriterion("`desc` not like", value, "desc");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDescIn(List<String> values) {
            addCriterion("`desc` in", values, "desc");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDescNotIn(List<String> values) {
            addCriterion("`desc` not in", values, "desc");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDescBetween(String value1, String value2) {
            addCriterion("`desc` between", value1, value2, "desc");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDescNotBetween(String value1, String value2) {
            addCriterion("`desc` not between", value1, value2, "desc");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPidEqualTo(Integer value) {
            addCriterion("pid =", value, "pid");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andPidEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("pid = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPidNotEqualTo(Integer value) {
            addCriterion("pid <>", value, "pid");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andPidNotEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("pid <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPidGreaterThan(Integer value) {
            addCriterion("pid >", value, "pid");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andPidGreaterThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("pid > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pid >=", value, "pid");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andPidGreaterThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("pid >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPidLessThan(Integer value) {
            addCriterion("pid <", value, "pid");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andPidLessThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("pid < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("pid <=", value, "pid");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andPidLessThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("pid <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPidIn(List<Integer> values) {
            addCriterion("pid in", values, "pid");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPidNotIn(List<Integer> values) {
            addCriterion("pid not in", values, "pid");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIconUrlIsNull() {
            addCriterion("icon_url is null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIconUrlIsNotNull() {
            addCriterion("icon_url is not null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIconUrlEqualTo(String value) {
            addCriterion("icon_url =", value, "iconUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andIconUrlEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("icon_url = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIconUrlNotEqualTo(String value) {
            addCriterion("icon_url <>", value, "iconUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andIconUrlNotEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("icon_url <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIconUrlGreaterThan(String value) {
            addCriterion("icon_url >", value, "iconUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andIconUrlGreaterThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("icon_url > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIconUrlGreaterThanOrEqualTo(String value) {
            addCriterion("icon_url >=", value, "iconUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andIconUrlGreaterThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("icon_url >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIconUrlLessThan(String value) {
            addCriterion("icon_url <", value, "iconUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andIconUrlLessThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("icon_url < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIconUrlLessThanOrEqualTo(String value) {
            addCriterion("icon_url <=", value, "iconUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andIconUrlLessThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("icon_url <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIconUrlLike(String value) {
            addCriterion("icon_url like", value, "iconUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIconUrlNotLike(String value) {
            addCriterion("icon_url not like", value, "iconUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIconUrlIn(List<String> values) {
            addCriterion("icon_url in", values, "iconUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIconUrlNotIn(List<String> values) {
            addCriterion("icon_url not in", values, "iconUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIconUrlBetween(String value1, String value2) {
            addCriterion("icon_url between", value1, value2, "iconUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andIconUrlNotBetween(String value1, String value2) {
            addCriterion("icon_url not between", value1, value2, "iconUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPicUrlIsNull() {
            addCriterion("pic_url is null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPicUrlIsNotNull() {
            addCriterion("pic_url is not null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPicUrlEqualTo(String value) {
            addCriterion("pic_url =", value, "picUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andPicUrlEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("pic_url = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPicUrlNotEqualTo(String value) {
            addCriterion("pic_url <>", value, "picUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andPicUrlNotEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("pic_url <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPicUrlGreaterThan(String value) {
            addCriterion("pic_url >", value, "picUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andPicUrlGreaterThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("pic_url > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("pic_url >=", value, "picUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andPicUrlGreaterThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("pic_url >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPicUrlLessThan(String value) {
            addCriterion("pic_url <", value, "picUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andPicUrlLessThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("pic_url < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPicUrlLessThanOrEqualTo(String value) {
            addCriterion("pic_url <=", value, "picUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andPicUrlLessThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("pic_url <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPicUrlLike(String value) {
            addCriterion("pic_url like", value, "picUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPicUrlNotLike(String value) {
            addCriterion("pic_url not like", value, "picUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPicUrlIn(List<String> values) {
            addCriterion("pic_url in", values, "picUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPicUrlNotIn(List<String> values) {
            addCriterion("pic_url not in", values, "picUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPicUrlBetween(String value1, String value2) {
            addCriterion("pic_url between", value1, value2, "picUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andPicUrlNotBetween(String value1, String value2) {
            addCriterion("pic_url not between", value1, value2, "picUrl");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andLevelIsNull() {
            addCriterion("`level` is null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andLevelIsNotNull() {
            addCriterion("`level` is not null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andLevelEqualTo(String value) {
            addCriterion("`level` =", value, "level");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andLevelEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`level` = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andLevelNotEqualTo(String value) {
            addCriterion("`level` <>", value, "level");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andLevelNotEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`level` <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andLevelGreaterThan(String value) {
            addCriterion("`level` >", value, "level");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andLevelGreaterThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`level` > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`level` >=", value, "level");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andLevelGreaterThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`level` >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andLevelLessThan(String value) {
            addCriterion("`level` <", value, "level");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andLevelLessThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`level` < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("`level` <=", value, "level");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andLevelLessThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("`level` <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andLevelLike(String value) {
            addCriterion("`level` like", value, "level");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andLevelNotLike(String value) {
            addCriterion("`level` not like", value, "level");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andLevelIn(List<String> values) {
            addCriterion("`level` in", values, "level");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andLevelNotIn(List<String> values) {
            addCriterion("`level` not in", values, "level");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andLevelBetween(String value1, String value2) {
            addCriterion("`level` between", value1, value2, "level");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("`level` not between", value1, value2, "level");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andSortOrderIsNull() {
            addCriterion("sort_order is null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andSortOrderIsNotNull() {
            addCriterion("sort_order is not null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andSortOrderEqualTo(Byte value) {
            addCriterion("sort_order =", value, "sortOrder");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andSortOrderEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("sort_order = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andSortOrderNotEqualTo(Byte value) {
            addCriterion("sort_order <>", value, "sortOrder");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andSortOrderNotEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("sort_order <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andSortOrderGreaterThan(Byte value) {
            addCriterion("sort_order >", value, "sortOrder");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andSortOrderGreaterThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("sort_order > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andSortOrderGreaterThanOrEqualTo(Byte value) {
            addCriterion("sort_order >=", value, "sortOrder");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andSortOrderGreaterThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("sort_order >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andSortOrderLessThan(Byte value) {
            addCriterion("sort_order <", value, "sortOrder");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andSortOrderLessThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("sort_order < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andSortOrderLessThanOrEqualTo(Byte value) {
            addCriterion("sort_order <=", value, "sortOrder");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andSortOrderLessThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("sort_order <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andSortOrderIn(List<Byte> values) {
            addCriterion("sort_order in", values, "sortOrder");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andSortOrderNotIn(List<Byte> values) {
            addCriterion("sort_order not in", values, "sortOrder");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andSortOrderBetween(Byte value1, Byte value2) {
            addCriterion("sort_order between", value1, value2, "sortOrder");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andSortOrderNotBetween(Byte value1, Byte value2) {
            addCriterion("sort_order not between", value1, value2, "sortOrder");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andAddTimeEqualTo(LocalDateTime value) {
            addCriterion("add_time =", value, "addTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andAddTimeEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("add_time = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andAddTimeNotEqualTo(LocalDateTime value) {
            addCriterion("add_time <>", value, "addTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andAddTimeNotEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("add_time <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andAddTimeGreaterThan(LocalDateTime value) {
            addCriterion("add_time >", value, "addTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andAddTimeGreaterThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("add_time > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andAddTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("add_time >=", value, "addTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andAddTimeGreaterThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("add_time >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andAddTimeLessThan(LocalDateTime value) {
            addCriterion("add_time <", value, "addTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andAddTimeLessThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("add_time < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andAddTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("add_time <=", value, "addTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andAddTimeLessThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("add_time <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andAddTimeIn(List<LocalDateTime> values) {
            addCriterion("add_time in", values, "addTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andAddTimeNotIn(List<LocalDateTime> values) {
            addCriterion("add_time not in", values, "addTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andAddTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andAddTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andUpdateTimeEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("update_time = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andUpdateTimeNotEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("update_time <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andUpdateTimeGreaterThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("update_time > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andUpdateTimeGreaterThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("update_time >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andUpdateTimeLessThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("update_time < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andUpdateTimeLessThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("update_time <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andDeletedEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("deleted = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andDeletedNotEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("deleted <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andDeletedGreaterThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("deleted > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andDeletedGreaterThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("deleted >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andDeletedLessThanColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("deleted < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andDeletedLessThanOrEqualToColumn(DtsShopCategoryEntity.Column column) {
            addCriterion(new StringBuilder("deleted <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }

        public DtsShopCategoryEntityExample.Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (DtsShopCategoryEntityExample.Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dts_category
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends DtsShopCategoryEntityExample.GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private DtsShopCategoryEntityExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(DtsShopCategoryEntityExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andIf(boolean ifAdd, DtsShopCategoryEntityExample.Criteria.ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopCategoryEntityExample.Criteria andLogicalDeleted(boolean deleted) {
            return deleted ? andDeletedEqualTo(DtsShopCategoryEntity.IS_DELETED) : andDeletedNotEqualTo(DtsShopCategoryEntity.IS_DELETED);
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table dts_category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table dts_category
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            DtsShopCategoryEntityExample.Criteria add(DtsShopCategoryEntityExample.Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dts_category
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
