package com.qiguliuxing.dts.db.domain;

import java.util.ArrayList;
import java.util.List;

public class DtsShopExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    protected List<DtsShopExample.Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    public DtsShopExample() {
        oredCriteria = new ArrayList<DtsShopExample.Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    public List<DtsShopExample.Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    public void or(DtsShopExample.Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    public DtsShopExample.Criteria or() {
        DtsShopExample.Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public DtsShopExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public DtsShopExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    public DtsShopExample.Criteria createCriteria() {
        DtsShopExample.Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    protected DtsShopExample.Criteria createCriteriaInternal() {
        DtsShopExample.Criteria criteria = new DtsShopExample.Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static DtsShopExample.Criteria newAndCreateCriteria() {
        DtsShopExample example = new DtsShopExample();
        return example.createCriteria();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<DtsShopExample.Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<DtsShopExample.Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<DtsShopExample.Criterion> getAllCriteria() {
            return criteria;
        }

        public List<DtsShopExample.Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new DtsShopExample.Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new DtsShopExample.Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new DtsShopExample.Criterion(condition, value1, value2));
        }

        public DtsShopExample.Criteria andIdIsNull() {
            addCriterion("id is null");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andIdEqualToColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andIdNotEqualToColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andIdGreaterThanColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andIdGreaterThanOrEqualToColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andIdLessThanColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andIdLessThanOrEqualToColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andOrderIdEqualToColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("order_id = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andOrderIdNotEqualToColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("order_id <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andOrderIdGreaterThanColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("order_id > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andOrderIdGreaterThanOrEqualToColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("order_id >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andOrderIdLessThanColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("order_id < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andOrderIdLessThanOrEqualToColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("order_id <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("order_id in", values, "orderId");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("order_id not in", values, "orderId");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andIsHotEqualTo(Boolean value) {
            addCriterion("is_hot =", value, "isHot");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andPhoneNumEqualTo(String value){
            addCriterion("phone_num =",value,"phoneNum");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andDeletedEqualToColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("deleted = ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andDeletedNotEqualToColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("deleted <> ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andDeletedGreaterThanColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("deleted > ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andDeletedGreaterThanOrEqualToColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("deleted >= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andDeletedLessThanColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("deleted < ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (DtsShopExample.Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andDeletedLessThanOrEqualToColumn(DtsShop.Column column) {
            addCriterion(new StringBuilder("deleted <= ").append(column.getEscapedColumnName()).toString());
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (DtsShopExample.Criteria) this;
        }

        public DtsShopExample.Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (DtsShopExample.Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dts_groupon
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends DtsShopExample.GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private DtsShopExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(DtsShopExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andIf(boolean ifAdd, DtsShopExample.Criteria.ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public DtsShopExample.Criteria andLogicalDeleted(boolean deleted) {
            return deleted ? andDeletedEqualTo(DtsShop.IS_DELETED) : andDeletedNotEqualTo(DtsShop.IS_DELETED);
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table dts_groupon
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table dts_groupon
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            DtsShopExample.Criteria add(DtsShopExample.Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dts_groupon
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
