package com.qiguliuxing.dts.db.domain;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

/**
 * 商铺产品类目表
 * 
 * @author chenshun
 * @email sunlightcs@gmail.com
 * @date 2020-06-29 15:20:24
 */
public class DtsShopCategoryEntity implements Serializable {
	private static final long serialVersionUID = 1L;

	public static final Boolean NOT_DELETED = false;

	public static final Boolean IS_DELETED = true;
	/**
	 * 商铺类目id
	 */
	private Integer id;
	/**
	 * 关键字
	 */
	private String keywords;
	/**
	 * 描述
	 */
	private String desc;
	/**
	 * 名称
	 */
	private String name;
	/**
	 * 缩略图url
	 */
	private String iconUrl;
	/**
	 * 大图url
	 */
	private String picUrl;
	/**
	 * 父级id
	 */
	private Integer pid;
	/**
	 * 类目等级
	 */
	private String level;
	/**
	 * 
	 */
	private Integer sortOrder;
	/**
	 * 所属店铺id
	 */
	private Integer shopId;
	/**
	 * 创建时间
	 * @return
	 */
	private LocalDateTime addTime;
	/**
	 * 更新时间
	 * @return
	 */
	private LocalDateTime updateTime;

	/**
	 * 逻辑删除
	 * @return
	 */
	private Boolean deleted;


	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIconUrl() {
		return iconUrl;
	}

	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl;
	}

	public String getPicUrl() {
		return picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getLevel() {
		return level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public Integer getSortOrder() {
		return sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	public Integer getShopId() {
		return shopId;
	}

	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	public LocalDateTime getAddTime() {
		return addTime;
	}

	public void setAddTime(LocalDateTime addTime) {
		this.addTime = addTime;
	}

	public LocalDateTime getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public enum Column {
		id("id", "id", "INTEGER", false),
		name("name", "name", "VARCHAR", true),
		keywords("keywords", "keywords", "VARCHAR", false),
		desc("desc", "desc", "VARCHAR", true),
		pid("pid", "pid", "INTEGER", false),
		iconUrl("icon_url", "iconUrl", "VARCHAR", false),
		picUrl("pic_url", "picUrl", "VARCHAR", false),
		level("level", "level", "VARCHAR", true),
		sortOrder("sort_order", "sortOrder", "TINYINT", false),
		shopId("shop_id", "shopId", "INTEGER", false),
		addTime("add_time", "addTime", "TIMESTAMP", false),
		updateTime("update_time", "updateTime", "TIMESTAMP", false),
		deleted("deleted", "deleted", "TINYINT", false);

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		private static final String BEGINNING_DELIMITER = "`";

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		private static final String ENDING_DELIMITER = "`";

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		private final String column;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		private final boolean isColumnNameDelimited;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		private final String javaProperty;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		private final String jdbcType;

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public String value() {
			return this.column;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public String getValue() {
			return this.column;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public String getJavaProperty() {
			return this.javaProperty;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public String getJdbcType() {
			return this.jdbcType;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
			this.column = column;
			this.javaProperty = javaProperty;
			this.jdbcType = jdbcType;
			this.isColumnNameDelimited = isColumnNameDelimited;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public String desc() {
			return this.getEscapedColumnName() + " DESC";
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public String asc() {
			return this.getEscapedColumnName() + " ASC";
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public static DtsCategory.Column[] excludes(DtsCategory.Column... excludes) {
			ArrayList<DtsCategory.Column> columns = new ArrayList<>(Arrays.asList(DtsCategory.Column.values()));
			if (excludes != null && excludes.length > 0) {
				columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
			}
			return columns.toArray(new DtsCategory.Column[]{});
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table dts_category
		 *
		 * @mbg.generated
		 * @project https://github.com/itfsw/mybatis-generator-plugin
		 */
		public String getEscapedColumnName() {
			if (this.isColumnNameDelimited) {
				return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
			} else {
				return this.column;
			}
		}
	}
}
